language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - 0.5
    - nightly
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.checkout("MbedTLS")'
    - julia -e 'Pkg.test("Requests", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Requests")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
